

# Statistics
Distributions S49 Statistical computing with R




> Never try to teach a pig to sing; it wastes your time and it annoys the pig.
> -- Paul Dickson


> If debugging is the process of removing software bugs, then programming must be the process of putting them in.
> -- Edsger Dijkstra

> Measuring programmin progress by lines of code is like measuring aircraft building progress by weight.
> -- Bill Gates

> There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other was is to make it so complicated that there are no obvious deficiencies. The first method is far more difficult.
> -- C.A.R Hoare

> Those who don't know how to code soon will be in the same position as those who couldn't read or write 200 years ago.
> -- Shereef Bishay

> Do. Or do not. There is no try.
> -- Yoda

> Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.
> -- Martin Golding

> One of my most productive days was throwing away 1000 lines of code.
> -- Ken Thompson

> Caution: Cape does not enable user to fly.
> -- Batman costume warning label



> Any code of your own that you haven't looked at for six or more months might as well have been written by someone else.
> -- Eagleson's law

> Beware of bugs in the above code; I have only proved it correct, not tried it.
> -- Donald E. Knuth

> Good code is its own best documentation. As you’re about to add a comment, ask yourself, "How can I improve the code so that this comment isn’t needed?
> -- Steve McConnell

> He's turned his life around. He used to be depressed and miserable. Now he's miserable and depressed.
> -- David Frost

> When someone says: 'I want a programming language in which I need only say what I wish done', give him a lollipop.
> -- Alan J. Perlis

> // Dear future me. Please forgive me.
> // I can’t even begin to express how sorry I am.
> -- Anonymous Code Comment

> You might not thing that programmers are artists, but programming is an extremely creative profession. It's logic based creativity.
> -- John Romero

> When the only tool you have is a hammer, everything looks like a nail.
> -- Abraham Maslow

> Be quick, but don't hurry.
> -- John Wooden
